<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 2,
                'title' => 'Dashboard',
                'url' => '/admin',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-05-31 22:17:38',
                'updated_at' => '2016-06-01 20:24:01',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 2,
                'title' => 'Media',
                'url' => '/admin/media',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-05-31 22:18:08',
                'updated_at' => '2017-01-04 16:00:17',
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 2,
                'title' => 'Posts',
                'url' => '/admin/posts',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-12-27 16:55:12',
                'updated_at' => '2017-01-04 16:00:15',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 2,
                'title' => 'Users',
                'url' => '/admin/users',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-05-31 22:19:16',
                'updated_at' => '2017-01-04 16:00:17',
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 2,
                'title' => 'Categories',
                'url' => '/admin/categories',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-05-31 22:19:38',
                'updated_at' => '2017-01-04 15:59:42',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 2,
                'title' => 'Pages',
                'url' => '/admin/pages',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-05-31 22:20:03',
                'updated_at' => '2017-01-04 16:00:17',
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 2,
                'title' => 'Roles',
                'url' => '/admin/roles',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => '',
                'parent_id' => NULL,
                'order' => 7,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-21 19:14:25',
                'updated_at' => '2017-01-04 16:00:17',
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Home',
                'url' => '/',
                'target' => '_self',
                'icon_class' => 'geekshop-home',
                'color' => '#f5f5f5',
                'parent_id' => NULL,
                'order' => 1,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-22 15:15:23',
                'updated_at' => '2016-10-22 20:28:23',
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'Gear & Gadgets',
                'url' => '/category/gear-gadgets',
                'target' => '_self',
                'icon_class' => 'geekshop-gadgets',
                'color' => '#e36e03',
                'parent_id' => NULL,
                'order' => 2,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-22 15:16:42',
                'updated_at' => '2016-11-06 16:32:21',
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Food & Drink',
                'url' => '/category/food-and-drink',
                'target' => '_self',
                'icon_class' => 'geekshop-food',
                'color' => '#eb9c2d',
                'parent_id' => NULL,
                'order' => 3,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-22 15:17:17',
                'updated_at' => '2016-11-06 16:32:36',
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Toys & Games',
                'url' => '/category/toys-and-games',
                'target' => '_self',
                'icon_class' => 'geekshop-games',
                'color' => '#189acb',
                'parent_id' => NULL,
                'order' => 4,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-22 15:18:21',
                'updated_at' => '2016-11-06 16:33:10',
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Geeky Stuff',
                'url' => '/category/geeky-stuff',
                'target' => '_self',
                'icon_class' => 'geekshop-geeky',
                'color' => '#1978b5',
                'parent_id' => NULL,
                'order' => 5,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-22 15:18:57',
                'updated_at' => '2016-11-06 16:33:27',
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Under $20',
                'url' => '/category/under-20',
                'target' => '_self',
                'icon_class' => 'geekshop-dollar',
                'color' => '#204054',
                'parent_id' => NULL,
                'order' => 6,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-22 15:19:56',
                'updated_at' => '2016-11-06 16:36:37',
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'More',
                'url' => '#_',
                'target' => '_self',
                'icon_class' => 'geekshop-more',
                'color' => '#1b3344',
                'parent_id' => NULL,
                'order' => 7,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-22 20:17:12',
                'updated_at' => '2016-11-06 16:36:56',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Home & Office',
                'url' => '/category/home-and-office',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#ffffff',
                'parent_id' => 14,
                'order' => 1,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-22 20:26:07',
                'updated_at' => '2016-10-22 20:48:10',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Wearables',
                'url' => '/category/wearables',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#ffffff',
                'parent_id' => 14,
                'order' => 2,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-22 20:27:16',
                'updated_at' => '2016-10-22 20:48:44',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Gifts For Men',
                'url' => '/category/gifts-for-men',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#ffffff',
                'parent_id' => 14,
                'order' => 3,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-22 20:27:32',
                'updated_at' => '2016-10-22 20:48:53',
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Gifts For Women',
                'url' => '/category/gifts-for-women',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#ffffff',
                'parent_id' => 14,
                'order' => 4,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-22 20:27:50',
                'updated_at' => '2016-10-22 20:49:45',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Gifts For Kids',
                'url' => '/category/gifts-for-kids',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#ffffff',
                'parent_id' => 14,
                'order' => 5,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-22 20:28:18',
                'updated_at' => '2016-10-22 20:49:04',
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 2,
                'title' => 'Products',
                'url' => '/admin/products',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-10-24 00:44:02',
                'updated_at' => '2017-01-04 15:59:40',
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 3,
                'title' => 'Gear & Gadgets',
                'url' => '/category/gear-gadgets',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-11-09 21:04:37',
                'updated_at' => '2016-11-09 23:40:42',
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => 3,
                'title' => 'Food & Drink',
                'url' => '/category/food-and-drink',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-11-09 21:04:53',
                'updated_at' => '2016-11-09 23:59:56',
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => 3,
                'title' => 'Toys & Games',
                'url' => '/category/toys-and-games',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-11-09 21:05:08',
                'updated_at' => '2016-11-10 00:00:03',
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => 3,
                'title' => 'Geeky Stuff',
                'url' => '/category/geeky-stuff',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-11-09 21:08:36',
                'updated_at' => '2016-11-10 00:00:08',
            ),
            24 => 
            array (
                'id' => 25,
                'menu_id' => 3,
                'title' => 'Under $20',
                'url' => '/category/under-20',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-11-09 21:08:51',
                'updated_at' => '2016-11-10 00:00:13',
            ),
            25 => 
            array (
                'id' => 26,
                'menu_id' => 3,
                'title' => 'Home & Office',
                'url' => '/category/home-and-office',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 14,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-11-09 21:09:06',
                'updated_at' => '2016-11-10 00:00:18',
            ),
            26 => 
            array (
                'id' => 27,
                'menu_id' => 3,
                'title' => 'Wearables',
                'url' => '/category/wearables',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 15,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-11-09 21:23:50',
                'updated_at' => '2016-11-10 00:00:24',
            ),
            27 => 
            array (
                'id' => 28,
                'menu_id' => 3,
                'title' => 'Gifts For Men',
                'url' => '/category/gifts-for-men',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-11-09 21:24:03',
                'updated_at' => '2016-11-10 00:00:29',
            ),
            28 => 
            array (
                'id' => 29,
                'menu_id' => 3,
                'title' => 'Gifts For Women',
                'url' => '/category/gifts-for-women',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 17,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-11-09 21:24:28',
                'updated_at' => '2016-11-10 00:00:34',
            ),
            29 => 
            array (
                'id' => 30,
                'menu_id' => 3,
                'title' => 'Gifts For Kids',
                'url' => '/category/gifts-for-kids',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 18,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-11-09 21:24:41',
                'updated_at' => '2016-11-10 00:00:40',
            ),
            30 => 
            array (
                'id' => 31,
                'menu_id' => 2,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-12-09 23:18:30',
                'updated_at' => '2016-12-29 04:35:51',
            ),
            31 => 
            array (
                'id' => 32,
                'menu_id' => 2,
                'title' => 'Menu Builder',
                'url' => '/admin/menus',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 31,
                'order' => 1,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-12-09 23:18:30',
                'updated_at' => '2016-12-11 19:29:24',
            ),
            32 => 
            array (
                'id' => 33,
                'menu_id' => 2,
                'title' => 'Database',
                'url' => '/admin/database',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 31,
                'order' => 2,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-12-09 23:18:30',
                'updated_at' => '2016-12-11 19:29:24',
            ),
            33 => 
            array (
                'id' => 34,
                'menu_id' => 2,
                'title' => 'Settings',
                'url' => '/admin/settings',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 10,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2016-12-09 23:18:30',
                'updated_at' => '2016-12-29 04:35:51',
            ),
            34 => 
            array (
                'id' => 35,
                'menu_id' => 4,
                'title' => 'Home',
                'url' => '/',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2017-01-04 16:03:27',
                'updated_at' => '2017-01-30 15:12:53',
            ),
            35 => 
            array (
                'id' => 36,
                'menu_id' => 4,
                'title' => 'Contact',
                'url' => '/page/contact',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2017-01-04 16:03:39',
                'updated_at' => '2017-01-30 15:12:53',
            ),
            36 => 
            array (
                'id' => 37,
                'menu_id' => 4,
                'title' => 'About',
                'url' => '/page/about',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2017-01-04 16:03:49',
                'updated_at' => '2017-01-30 15:12:53',
            ),
            37 => 
            array (
                'id' => 38,
                'menu_id' => 4,
                'title' => 'Facebook',
                'url' => 'https://www.facebook.com/thedevdojo',
                'target' => '_blank',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2017-01-04 16:04:45',
                'updated_at' => '2017-01-30 15:12:53',
            ),
            38 => 
            array (
                'id' => 39,
                'menu_id' => 4,
                'title' => 'Twitter',
                'url' => 'https://twitter.com/thedevdojo',
                'target' => '_blank',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2017-01-04 16:05:20',
                'updated_at' => '2017-01-30 15:12:53',
            ),
            39 => 
            array (
                'id' => 40,
                'menu_id' => 4,
                'title' => 'Blog',
                'url' => '/blog',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2017-01-30 15:12:49',
                'updated_at' => '2017-01-30 15:12:53',
            ),
            40 => 
            array (
                'id' => 41,
                'menu_id' => 1,
                'title' => 'Blog',
                'url' => '/blog',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#ffffff',
                'parent_id' => 14,
                'order' => 6,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2017-02-04 14:35:45',
                'updated_at' => '2017-02-04 14:36:18',
            ),
            41 => 
            array (
                'id' => 42,
                'menu_id' => 2,
                'title' => 'Hooks',
                'url' => '/admin/hooks',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 99,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2017-09-18 21:55:03',
                'updated_at' => '2017-09-18 21:55:03',
            ),
            42 => 
            array (
                'id' => 43,
                'menu_id' => 2,
                'title' => 'Themes',
                'url' => '/admin/themes',
                'target' => '_self',
                'icon_class' => 'voyager-paint-bucket',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 98,
                'route' => NULL,
                'parameters' => NULL,
                'created_at' => '2017-12-06 13:36:02',
                'updated_at' => '2017-12-06 13:36:02',
            ),
        ));
        
        
    }
}