<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Paper Towel USB Charger Hub',
                'seo_title' => 'Paper Towel USB Charger Hub',
                'image' => 'products/October2016/18CQEWYvusS3IZImyEQS.jpg',
                'description' => 'Ever find yourself at a loss for USB ports? Well now this paper towel holder can serve as a USB charging station for all your devices!',
                'body' => '',
                'price' => 49.99,
                'purchase_url' => '',
                'slug' => 'paper-towel-usb-charger-hub',
                'meta_description' => 'Paper Towel USB charging station.',
                'meta_keywords' => 'usb, usb charging station, paper towel use, paper towel use charging station',
                'active' => 1,
                'featured' => 0,
                'category_id' => 1,
                'created_at' => '2016-10-24 04:08:19',
                'updated_at' => '2016-10-29 22:48:15',
                'related' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Programming Language Playing Cards',
                'seo_title' => 'Programming Language Playing Cards',
                'image' => 'products/October2016/FD0mUhx4feCnzvuttTAH.jpg',
                'description' => 'code:deck is a standard playing card deck sporting a stylish modern design.
Each individual card features a code snippet describing it in a different programming language.',
                'body' => '<p><img src="../../../storage/products/October2016/NZs1F6zvwQhpybJnOav3.jpg" alt="" width="100%" height="auto" /></p>
<p><img src="../../../storage/products/October2016/DRNkhTqrSeanDBtmw4NG.jpg" alt="" width="100%" height="auto" /></p>',
                'price' => 10.0,
                'purchase_url' => '',
                'slug' => 'programming-language-playing-cards',
                'meta_description' => 'Programming Language Playing Cards',
                'meta_keywords' => 'playing cards, programming cards, programming playing cards',
                'active' => 1,
                'featured' => 1,
                'category_id' => 2,
                'created_at' => '2016-10-24 13:25:38',
                'updated_at' => '2016-11-29 19:38:20',
                'related' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Darth Vader Fire Pit',
                'seo_title' => 'Darth Vader Fire Pit',
                'image' => 'products/October2016/oBI8OUMQ3paP3QzeKiqN.jpg',
                'description' => 'Let the dark side burn with this awesome fire pit. Show off your true Star Wars geekiness by bringing this bad boy to your next camp out.',
                'body' => '',
                'price' => 444.09,
                'purchase_url' => 'https://www.etsy.com/listing/263087928/darth-vader-star-wars-inspired-wood',
                'slug' => 'darth-vader-fire-pit',
                'meta_description' => 'Star Wars Darth Vader Fire Pit',
                'meta_keywords' => 'Darth Vader Fire Pit, fire pit, star wars',
                'active' => 1,
                'featured' => 0,
                'category_id' => 1,
                'created_at' => '2016-10-30 13:05:01',
                'updated_at' => '2016-10-30 13:05:01',
                'related' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Star Wars Darth Vader Mister',
                'seo_title' => 'Star Wars Darth Vader Mister',
                'image' => 'products/October2016/OYtI1fiCmQ3N7zNzYi3i.jpg',
                'description' => 'Want to spook up your haunted house with a geeky Darth Vader Mister. Then you\'ve got to checkout these cool Star Wars Misters. Just add tap water and let the eerie mist begin.',
                'body' => '<p><img src="../../../storage/products/October2016/Pav4VExWtEuC2f0914Vi.jpg" alt="" width="640" height="534" /></p>',
                'price' => 11.95,
                'purchase_url' => 'https://www.amazon.com/dp/B011BD7GUG/',
                'slug' => 'star-wars-darth-vader-mister',
                'meta_description' => 'A geeky Darth Vader Mister',
                'meta_keywords' => 'Darth Vader Mister, Mister, Darth Vader, Star wars, halloween',
                'active' => 1,
                'featured' => 0,
                'category_id' => 3,
                'created_at' => '2016-10-30 13:15:55',
                'updated_at' => '2017-07-09 17:44:48',
                'related' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Kylo Ren Lightsaber Room Light',
                'seo_title' => '',
                'image' => 'products/October2016/oSrVgdWIZ7eWC22Jkkek.jpg',
                'description' => 'The final challenge in becoming a Sith is to build your own Lightsaber. Construct and display your own Kylo Ren Lightsaber. With awesome lightsaber sound effects and remote control!.',
                'body' => '',
                'price' => 11.03,
                'purchase_url' => 'https://www.amazon.com/dp/B016SRSITS/',
                'slug' => 'kylo-ren-lightsaber-room-light',
                'meta_description' => 'Kylo Ren Lightsaber Room Light',
                'meta_keywords' => 'Kylo Ren Lightsaber Room Light',
                'active' => 1,
                'featured' => 0,
                'category_id' => 3,
                'created_at' => '2016-10-30 13:56:31',
                'updated_at' => '2017-07-09 17:44:48',
                'related' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Star Wars Tie Fighter Desk',
                'seo_title' => '',
                'image' => 'products/October2016/eBwADt9Ebd43I3V6pbZb.jpg',
                'description' => 'Known throughout the galaxy as the sentry ships of choice for the Death Star, this desk is sunken in, creating two sides that will keep projects on the desk and off the floor.',
                'body' => '',
                'price' => 399.99,
                'purchase_url' => 'http://www.roomstogokids.com/product/Special/AsAdvertised/36111615/',
                'slug' => 'star-wars-tie-fighter-desk',
                'meta_description' => 'Star Wars Tie Fighter Desk',
                'meta_keywords' => 'Star Wars Tie Fighter Desk',
                'active' => 1,
                'featured' => 0,
                'category_id' => 3,
                'created_at' => '2016-10-30 14:00:38',
                'updated_at' => '2016-10-30 14:01:47',
                'related' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Man Buckets',
                'seo_title' => '',
                'image' => 'products/October2016/WXC54qMurVkroXHUPNpB.jpg',
                'description' => 'These are the ultimate gift for a man. You can choose which man bucket is right for you. There is the Beer Bucket, the Snack Bucket, the Wilderness Bucket, and much more.',
                'body' => '<p><img src="../../../storage/products/October2016/Ks1AZ5t62s8fSsrhdUU7.jpg" alt="" width="640" height="533" /></p>
<p><img src="../../../storage/products/October2016/4i5o1bpXv5vQGUmlnc8I.jpg" alt="" width="640" height="533" /></p>
<p><img src="../../../storage/products/October2016/13lBwlKAv2xuYgxCVLbk.jpg" alt="" width="640" height="533" /></p>
<p><img src="../../../storage/products/October2016/xXmBGZZ321e9vrWHyUCA.jpg" alt="" width="640" height="534" /></p>',
                'price' => 58.99,
                'purchase_url' => 'http://www.manbuckets.com/',
                'slug' => 'man-buckets',
                'meta_description' => 'Get the man bucket for your man',
                'meta_keywords' => 'man bucket, bucket',
                'active' => 1,
                'featured' => 1,
                'category_id' => 4,
                'created_at' => '2016-10-30 20:41:57',
                'updated_at' => '2016-11-29 19:38:16',
                'related' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Drink Counting Koozie',
                'seo_title' => '',
                'image' => 'products/October2016/KX106A5ucSv5u0XJFGHt.jpg',
                'description' => 'No longer will you have to worry about how many beers you\'ve consumed. Now your koozie can let you know. The bevometer will count how many drinks or beers that you\'ve consumed.',
                'body' => '',
                'price' => 10.99,
                'purchase_url' => 'https://www.amazon.com/dp/B00LEWIGN6/',
                'slug' => 'drink-counting-koozie',
                'meta_description' => 'Beer counting koozie',
                'meta_keywords' => 'beer counting koozie, drink counting koozie, counting koozie, koozie',
                'active' => 1,
                'featured' => 0,
                'category_id' => 4,
                'created_at' => '2016-10-30 20:46:54',
                'updated_at' => '2016-10-30 20:46:54',
                'related' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Hot Sauce Subscription Box',
                'seo_title' => '',
                'image' => 'products/October2016/jnM7UM4zgm3P36ERWOfa.jpg',
                'description' => 'Do you love hot sauce. If so you\'ll need to get a subscription the this hot sauce service. Give your meals a fiery kick with these different variations of hot sauces.',
                'body' => '<p><img src="/storage/products/October2016/61eMuAN2MQDySPa6Otkw.jpg" alt="" width="565" height="471" /></p>
<p><img src="/storage/products/October2016/mpGezOQrKkcYXRk89NJr.jpg" alt="" width="565" height="471" /></p>',
                'price' => 29.95,
                'purchase_url' => 'http://www.fuegobox.com/subscribe/',
                'slug' => 'hot-sauce-subscription-box',
                'meta_description' => 'Hot Sauce Subscription box',
                'meta_keywords' => 'hot sauce, hot sauce service, hot sauce subscription service, hot sauce box',
                'active' => 1,
                'featured' => 0,
                'category_id' => 4,
                'created_at' => '2016-10-30 20:52:40',
                'updated_at' => '2017-01-02 04:29:27',
                'related' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'BBQ Briefcase',
                'seo_title' => 'BBQ Briefcase',
                'image' => 'products/November2016/aQgrYwQ5WiYqdYgAIjtp.jpg',
                'description' => 'You can enjoy a BBQ where ever you go now with this awesome portable BBQ Briefcase. Simply fold it open and you\'re ready to start cooking some delicious food.',
                'body' => '',
                'price' => 53.99,
                'purchase_url' => 'https://www.amazon.com/dp/B00J2WZ6S8/',
                'slug' => 'bbq-briefcase',
                'meta_description' => 'Be the coolest guy at your next BBQ with this BBQ Briefcase.',
                'meta_keywords' => 'BBQ, BBQ Briefcase, portable BBQ',
                'active' => 1,
                'featured' => 0,
                'category_id' => 1,
                'created_at' => '2016-11-07 16:08:45',
                'updated_at' => '2017-07-09 17:44:49',
                'related' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Space Up Bed And Storage',
                'seo_title' => '',
                'image' => 'products/November2016/uNylTSsvQd8jiNXS3YiY.jpg',
                'description' => 'The Space Up Bed will save you so much room and it will help keep your room as clean as possible. There is a ton of storage under the bed including drawers.',
                'body' => '<p><img src="/storage/products/November2016/czgm9LUb6iiemIOijtig.jpg" alt="" width="100%" height="auto" /></p>
<p><img src="/storage/products/November2016/cfFhebqhyeLKBQ9TBGz9.jpg" alt="" width="100%" height="auto" /></p>',
                'price' => 1127.0,
                'purchase_url' => 'https://www.amazon.com/dp/B00N3WTUN0/',
                'slug' => 'space-up-bed-and-storage',
                'meta_description' => 'The space up bed is the ultimate bed that folds up and folds down. Underneath the bed you can use to store clothes and anything else.',
                'meta_keywords' => 'Store up Bed, bed, fold up bed',
                'active' => 1,
                'featured' => 0,
                'category_id' => 5,
                'created_at' => '2016-11-07 16:15:32',
                'updated_at' => '2017-07-09 17:44:50',
                'related' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Tea Rex Mug',
                'seo_title' => 'Tea Rex Mug',
                'image' => 'products/November2016/MiAasFLX4qVfsNDuK9DS.jpg',
                'description' => 'Sippin tea out of the Tea Rex mug couldn\'t be cooler. If you are a fan of puns, you gotta get this mug to show off to all your friends or purchase it as a gift.',
                'body' => '',
                'price' => 16.0,
                'purchase_url' => 'https://www.etsy.com/listing/172173944/tea-rex-mug-t-rex-dinosaur-mug-gift-for',
                'slug' => 'tea-rex-mug',
                'meta_description' => 'Tea Rex Mug',
                'meta_keywords' => 'Tea Rex Mug, Mug, Tea Mug, Coffee Cup',
                'active' => 1,
                'featured' => 0,
                'category_id' => 5,
                'created_at' => '2016-11-07 16:18:59',
                'updated_at' => '2016-11-07 16:18:59',
                'related' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Darth Vader USB Charger',
                'seo_title' => 'Darth Vader USB Charger',
                'image' => 'products/November2016/zXAUVLQLrH1m7WzGL3Vh.jpg',
                'description' => 'Never under estimate the power of the dark side. With this darth vader USB charger you can gaurantee that your devices are fully charged and ready to go.',
                'body' => '<p><iframe title="Star Wars Darth Vader USB Car Charger from ThinkGeek" src="https://www.youtube.com/embed/lJDHaV3t538?wmode=opaque&amp;theme=dark" width="560" height="315" frameborder="0" allowfullscreen=""></iframe></p>',
                'price' => 14.99,
                'purchase_url' => 'http://www.thinkgeek.com/product/iqih/',
                'slug' => 'darth-vader-usb-charger',
                'meta_description' => 'Darth Vader USB Charger',
                'meta_keywords' => 'usb charger, star wars device, darth vader usb charger, star wars USB charger',
                'active' => 1,
                'featured' => 1,
                'category_id' => 3,
                'created_at' => '2016-11-12 16:36:31',
                'updated_at' => '2016-11-29 19:38:11',
                'related' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'R2D2 Mini Fridge',
                'seo_title' => 'R2D2 Mini Fridge',
                'image' => 'products/November2016/oM3IaPpFGnJ1hqD4gCy9.jpg',
                'description' => 'Keep your beverages cool with this out of this galaxy R2D2 mini fridge. This mini fridge will make your office look super retro and spacetastic!',
                'body' => '',
                'price' => 149.99,
                'purchase_url' => 'http://www.thinkgeek.com/product/ipsi/',
                'slug' => 'r2d2-mini-fridge',
                'meta_description' => 'R2D2 Mini Fridge',
                'meta_keywords' => 'mini fridge, r2d2 fridge',
                'active' => 1,
                'featured' => 1,
                'category_id' => 3,
                'created_at' => '2016-11-12 18:17:02',
                'updated_at' => '2016-11-29 19:37:50',
                'related' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Retro Gaming System',
                'seo_title' => 'Retro Gaming System',
                'image' => 'products/November2016/Ecx0HqsanLX0ihKG8Ahs.jpg',
                'description' => 'Do you love playing the old retro games for Super Nintendo, Nintendo, Sega, and many of the other old consoles. Well, you\'ll have to purchase this retro gaming system and enjoy all the old games you used to enjoy.',
                'body' => '',
                'price' => 160.03,
                'purchase_url' => 'https://www.amazon.com/gp/product/B00DZIX394/',
                'slug' => 'retro-gaming-system',
                'meta_description' => 'Retro Gaming System',
                'meta_keywords' => 'retro gaming system, super nintendo, nintendo',
                'active' => 1,
                'featured' => 0,
                'category_id' => 2,
                'created_at' => '2016-11-12 21:01:14',
                'updated_at' => '2016-11-12 21:01:14',
                'related' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Pretzel Chocolate Chip Cookie',
                'seo_title' => 'Pretzel Chocolate Chip Cookie',
                'image' => 'products/November2016/77KVu8NRiwKt1eKum6oa.jpg',
                'description' => 'Do you love Chocolate Chip cookies and Pretzels? If so you need the Salty n\' Sweet Pretzel Cookie Mix. Combine these 2 delicious snacks into the ultimate chocolate chip pretzel cookie.',
                'body' => '<p><img src="/storage/products/November2016/eRxgizMlzWvjzjRvK5AM.jpg" alt="" width="597" height="499" /></p>
<p><img src="/storage/products/November2016/7GhFYMdCksNAqeHiVaAk.jpg" alt="" width="599" height="500" /></p>
<p><img src="/storage/products/November2016/CQ8N5rT9URVogdbazI2N.jpg" alt="" width="635" height="530" /></p>',
                'price' => 9.0,
                'purchase_url' => 'https://www.etsy.com/listing/195025192/salty-n-sweet-pretzel-cookie-mix',
                'slug' => 'pretzel-chocolate-chip-cookie',
                'meta_description' => 'Chocolate Chip Pretzel Cookie',
                'meta_keywords' => 'chocolate chips, chocolate chip cookie, chocolate chip cookie pretzel, pretzel cookie',
                'active' => 1,
                'featured' => 0,
                'category_id' => 6,
                'created_at' => '2016-11-14 19:38:22',
                'updated_at' => '2016-11-14 19:39:23',
                'related' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Hot Sauce Challenge Pack',
                'seo_title' => 'Hot Sauce Challenge Pack',
                'image' => 'products/November2016/ZpO0wl6ABKKlfAPGS4O6.jpg',
                'description' => 'Put your taste buds to the test with this pack of 12 bottle hot sauces ranging from mild to insanely hot. This would make the perfect gift for anyone who loves hot sauce.',
                'body' => '',
                'price' => 23.99,
                'purchase_url' => 'https://www.vat19.com/item/hot-sauce-challenge-12-pack-book',
                'slug' => 'hot-sauce-challenge-pack',
                'meta_description' => 'Hot Sauce Challenge Pack',
                'meta_keywords' => 'hot sauce, hot sauce bottles',
                'active' => 1,
                'featured' => 0,
                'category_id' => 6,
                'created_at' => '2016-11-14 20:16:16',
                'updated_at' => '2016-11-14 20:16:16',
                'related' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Calm The Fuck Down Tea',
                'seo_title' => 'Calm The Fuck Down Tea',
                'image' => 'products/November2016/dyo61bE1SFPlVAfvMmhL.jpg',
                'description' => 'Calm the fuck down tea is perfect for, yep... Calming the fuck down. This will make the perfect gift for anyone who loves tea or for anyone who needs some stress relief.',
                'body' => '<p><img src="/storage/products/November2016/JhN4OeL6I754r6yWXqxr.jpg" alt="" width="640" height="533" /></p>
<p><img src="/storage/products/November2016/0LBVIVtQLhm8TePmMBO5.jpg" alt="" width="640" height="534" /></p>
<p><img src="/storage/products/November2016/VjB9zx7xRevfqbPaMdH7.jpg" alt="" width="640" height="533" /></p>',
                'price' => 13.0,
                'purchase_url' => 'https://www.firebox.com/Calm-the-Fck-Down-Tea/p7275',
                'slug' => 'calm-the-fuck-down-tea',
                'meta_description' => 'Calm The Fuck Down Tea',
                'meta_keywords' => 'tea, calm tea, calm down tea',
                'active' => 1,
                'featured' => 0,
                'category_id' => 6,
                'created_at' => '2016-11-14 20:20:11',
                'updated_at' => '2016-11-14 20:20:11',
                'related' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'World\'s Largest Arcade Machine',
                'seo_title' => 'World\'s Largest Arcade Machine',
                'image' => 'products/November2016/47kQv6IVwimBDx8Atker.jpg',
                'description' => 'Do regular size arcade games excite you? Well, if they do then this worlds largest arcade machine will have you leaping for joy. Literally! If you are not tall enough you may have to leap just to reach the controls.',
                'body' => '<p><img src="/storage/products/November2016/SbzaXnEMkY1wAng40CCl.jpg" alt="" width="640" height="533" /></p>
<p><img src="/storage/products/November2016/hSNQ8eJ57DbAYuNhighi.jpg" alt="" width="640" height="533" /></p>
<p><img src="/storage/products/November2016/lOxr60wpOxAhjgHPODIW.jpg" alt="" width="640" height="533" /></p>',
                'price' => 99000.0,
                'purchase_url' => 'http://www.hammacher.com/Product/12995',
                'slug' => 'words-largest-arcade-machine',
                'meta_description' => 'The worlds largest arcade machine',
                'meta_keywords' => 'arcade machine, large arcade machine, words largest arcade machine',
                'active' => 1,
                'featured' => 0,
                'category_id' => 3,
                'created_at' => '2016-11-17 14:55:07',
                'updated_at' => '2016-11-17 15:08:00',
                'related' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Nintendo Game Cartridge Flask',
                'seo_title' => 'Nintendo Game Cartridge Flask',
                'image' => 'products/November2016/0IWWGuU4Q0gpApb1nDwk.jpg',
                'description' => 'Did you used to love playing duck hunt as a kid and now you are more into drinking than playing video games. Well, Drunk Hunt is the game cartridge flask that you need to hold your alcohol.',
                'body' => '',
                'price' => 15.0,
                'purchase_url' => 'http://www.inkwhiskey.com/products/drunk-hunt',
                'slug' => 'nintendo-game-cartridge-flask',
                'meta_description' => 'Drunk Hunt Video Game Cartridge Flask',
                'meta_keywords' => 'drunk hunt, video game cartridge flash, video game flask, nintendo game flask',
                'active' => 1,
                'featured' => 0,
                'category_id' => 6,
                'created_at' => '2016-11-17 15:06:00',
                'updated_at' => '2017-01-03 20:21:10',
                'related' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'Electric Scooter Cooler',
                'seo_title' => 'Electric Scooter Cooler',
                'image' => 'products/November2016/pgKttha6MJaltbb5xjpw.png',
                'description' => 'Now you can cruise around on your scooter and bring your drinks with you. The electric scooter cooler is an electric scooter which has a cooler attached to it. Now you\'ll be drinking and scooting in style.',
                'body' => '',
                'price' => 925.0,
                'purchase_url' => 'https://www.amazon.com/gp/product/B008U1D74C/',
                'slug' => 'electric-scooter-cooler',
                'meta_description' => 'Electric Scooter Cooler',
                'meta_keywords' => 'scooter cooler, electric scooter cooler',
                'active' => 1,
                'featured' => 0,
                'category_id' => 6,
                'created_at' => '2016-11-17 15:15:17',
                'updated_at' => '2016-11-17 15:17:42',
                'related' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'Magnetic Smart Putty',
                'seo_title' => 'Magnetic Smart Putty',
                'image' => 'products/November2016/JkF39iRGhakGYTH6Nfnb.jpg',
                'description' => 'This magnetic smart putty will keep you entertained for hours. This smart putty can transform move and follow any kind of magnetic force. Mold the putty and move it with magnetic forces.',
                'body' => '',
                'price' => 14.99,
                'purchase_url' => 'https://www.vat19.com/item/magnetic-thinking-putty',
                'slug' => 'magnetic-smart-putty',
                'meta_description' => 'Magnetic smart putty',
                'meta_keywords' => 'smart putty, magnetic smart putty',
                'active' => 1,
                'featured' => 0,
                'category_id' => 7,
                'created_at' => '2016-11-17 15:22:06',
                'updated_at' => '2016-11-17 15:22:06',
                'related' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'Camera Lens Coffee Mug',
                'seo_title' => 'Camera Lens Coffee Mug',
                'image' => 'products/November2016/LjGRtaPvz1yMrRUvVNQC.jpg',
                'description' => 'This camera coffee mug will make the perfect gift for anyone who loves photography. This camera mug also has a holder for your favorite snacks. Never will you be tired while shooting photos with this mug.',
                'body' => '',
                'price' => 10.12,
                'purchase_url' => 'https://www.amazon.com/dp/B0058CW9UO/',
                'slug' => 'camera-lens-coffee-mug',
                'meta_description' => 'Camera Coffee Mug',
                'meta_keywords' => 'coffee mug, camera coffee mug',
                'active' => 1,
                'featured' => 0,
                'category_id' => 7,
                'created_at' => '2016-11-17 15:25:01',
                'updated_at' => '2017-07-09 17:44:50',
                'related' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'Floating Bookshelves',
                'seo_title' => 'Floating Bookshelves',
                'image' => 'products/November2016/bzwRVAE0fqHGZzVJqd9i.jpg',
                'description' => 'Your books don\'t need to take up space on the counter instead you can get these invisible hanging bookshelves and turn those books into a decoration piece.',
                'body' => '',
                'price' => 8.0,
                'purchase_url' => 'https://www.amazon.com/dp/B0053GBBJU/',
                'slug' => 'floating-bookshelves',
                'meta_description' => 'Floating Bookshelves',
                'meta_keywords' => 'floating bookshelf, bookshelf',
                'active' => 1,
                'featured' => 0,
                'category_id' => 7,
                'created_at' => '2016-11-17 15:26:35',
                'updated_at' => '2017-07-09 17:44:51',
                'related' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'Bath Tub Wine Glass Holder',
                'seo_title' => 'Bath Tub Wine Glass Holder',
                'image' => 'products/November2016/HHMm9UCyULNXMr3w1me0.jpg',
                'description' => 'Tired of having to hold your wine glass or bee while taking a bath. Well now you don\'t have to. With this holder you can kick back in your tub or shower and have your beverage sitting right next to you.',
                'body' => '<p><img src="/storage/products/November2016/8a5rNkCxyvFiaDbnwsWU.jpg" alt="" width="640" height="533" /></p>',
                'price' => 13.95,
                'purchase_url' => 'https://www.amazon.com/dp/B00MIINXB0/',
                'slug' => 'bath-tub-wine-glass-holder',
                'meta_description' => 'Bath Tub Wine Glass Holder',
                'meta_keywords' => 'Bath Tub Wine Glass Holder, Shower and bath drink holder',
                'active' => 1,
                'featured' => 0,
                'category_id' => 9,
                'created_at' => '2016-11-29 14:47:19',
                'updated_at' => '2016-11-29 14:47:19',
                'related' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'People I Want To Punch Journal',
                'seo_title' => 'People I Want To Punch Journal',
                'image' => 'products/November2016/iUlFuHbKJ3HccBobCFPw.jpg',
                'description' => 'Using this “people I want to punch in the face” journal you’ll have ample room to write down everyone who has ever made the mistake of crossing you – so you can plan your vengeance.',
                'body' => '<p><img src="/storage/products/November2016/Bi05Fa401MZRHjyKhDg0.jpg" alt="" width="640" height="533" /></p>',
                'price' => 15.0,
                'purchase_url' => 'https://www.etsy.com/listing/125464402/people-i-want-to-punch-in-the-face',
                'slug' => 'people-i-want-to-punch-journal',
                'meta_description' => 'People I Want To Punch Journal',
                'meta_keywords' => 'People I Want To Punch Journal',
                'active' => 1,
                'featured' => 0,
                'category_id' => 9,
                'created_at' => '2016-11-29 14:57:37',
                'updated_at' => '2016-11-29 14:57:37',
                'related' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'Starbucks Mocha Scented Candle',
                'seo_title' => 'Starbucks Mocha Scented Candle',
                'image' => 'products/November2016/VPVKCY0Mopqt0b4AbnMs.jpg',
                'description' => 'Make your living room the place to socialize while pretending to work on your novel by giving it a coffee shop vibe using this Starbucks mocha scented candle.',
                'body' => '<p><img src="/storage/products/November2016/Fjx5cVOkODwTmS6ugdLh.jpg" alt="" width="640" height="533" /></p>
<p><img src="/storage/products/November2016/8V33Yb7eAkCcrTTgu88m.jpg" alt="" width="640" height="533" /></p>',
                'price' => 12.0,
                'purchase_url' => '',
                'slug' => 'starbucks-mocha-scented-candle',
                'meta_description' => 'Starbucks Mocha Scented Candle',
                'meta_keywords' => 'Starbucks Mocha Scented Candle',
                'active' => 1,
                'featured' => 0,
                'category_id' => 9,
                'created_at' => '2016-11-29 15:00:02',
                'updated_at' => '2016-11-29 15:00:02',
                'related' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'Date Night Subscription Box',
                'seo_title' => 'Date Night Subscription Box',
                'image' => 'products/November2016/pQjaQzyYFg3UeEhZOAYi.jpg',
                'description' => 'The perfect stay-at-home date night subscription box. Each box comes packed with 5-7 goodies that include an interactive activity, snacks, and everything needed for a romantic evening at home.',
                'body' => '<p><img src="/storage/products/November2016/XtnjXzphVgKeDtopiZeU.jpg" alt="" /></p>
<p><img src="/storage/products/November2016/ova8dqaP7smZ2SaDVDUd.jpg" alt="" width="640" height="534" /></p>',
                'price' => 34.99,
                'purchase_url' => 'https://www.cratejoy.com/subscription-box/date-night-in/',
                'slug' => 'date-night-subscription-box',
                'meta_description' => 'Date Night Subscription Box',
                'meta_keywords' => 'Date Night Subscription Box',
                'active' => 1,
                'featured' => 0,
                'category_id' => 9,
                'created_at' => '2016-11-29 15:43:53',
                'updated_at' => '2016-11-29 15:46:01',
                'related' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'Shark Week Period Pouch',
                'seo_title' => 'Shark Week Period Pouch',
                'image' => 'products/November2016/b6KcGo88aifSBRZXKliq.jpg',
                'description' => 'Celebrate Shark Week more than once a year by storing your tampons and pads inside this period pouch. Each brightly colored pouch sports a black “Shark Week” logo and has a zippered opening for bloody quick access.',
                'body' => '<p><img src="/storage/products/November2016/qntuwrlYSOnAds4Djn6P.jpg" alt="" width="640" height="534" /></p>
<p><img src="/storage/products/November2016/QBLgYDYiMHfHKbT4xwT5.jpg" alt="" width="640" height="533" /></p>
<p><img src="/storage/products/November2016/owSiOmf3u9nXCxL4Xdua.jpg" alt="" width="640" height="533" /></p>',
                'price' => 11.95,
                'purchase_url' => 'https://www.etsy.com/listing/118622034/tampon-maxi-pad-holder-shark-week',
                'slug' => 'shark-week-period-pouch',
                'meta_description' => 'Shark Week Period Pouch',
                'meta_keywords' => 'Shark Week Period Pouch',
                'active' => 1,
                'featured' => 0,
                'category_id' => 9,
                'created_at' => '2016-11-29 15:49:49',
                'updated_at' => '2016-11-29 15:49:49',
                'related' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'Calligraphy Starter Kit',
                'seo_title' => 'Calligraphy Starter Kit',
                'image' => 'products/November2016/JxikXK9mcUKQbUPtncCy.jpg',
                'description' => 'Learn the art of putting ink to paper using this calligraphy starter kit. The kit includes an oblique calligraphy pen, ink dropper, practice vellum paper, a beginner friendly nib, and other tools of the trade for you to learn with ease.',
                'body' => '<p><img src="/storage/products/November2016/PDo9BhMda2knhCEkXAJd.jpg" alt="" width="640" height="534" /></p>',
                'price' => 45.0,
                'purchase_url' => 'https://www.etsy.com/listing/250694123/calligraphy-starter-kit-beginner',
                'slug' => 'calligraphy-starter-kit',
                'meta_description' => 'Calligraphy Starter Kit',
                'meta_keywords' => 'Calligraphy Starter Kit',
                'active' => 1,
                'featured' => 0,
                'category_id' => 9,
                'created_at' => '2016-11-29 15:52:06',
                'updated_at' => '2016-11-29 15:52:06',
                'related' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'Dark Side Coffee Roast',
                'seo_title' => 'Dark Side Coffee Roast',
                'image' => 'products/November2016/Nmgl4MTZgVcaPyD78gIr.jpg',
                'description' => 'Let the power of the Dark Side flow through you every morning by chugging down a potent cup of this Star Wars themed coffee. A full-bodied blend with a sharp and smoky taste no Sith Lord can resist.',
                'body' => '',
                'price' => 14.99,
                'purchase_url' => 'https://www.amazon.com/dp/B004HGBNI6/',
                'slug' => 'dark-side-coffee-roast',
                'meta_description' => 'Dark Side Coffee Roast',
                'meta_keywords' => 'Dark Side Coffee Roast',
                'active' => 1,
                'featured' => 0,
                'category_id' => 6,
                'created_at' => '2016-11-29 23:36:57',
                'updated_at' => '2016-11-29 23:36:57',
                'related' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'The Simpsons LEGO Kwik-E-Mart',
                'seo_title' => 'The Simpsons LEGO Kwik-E-Mart',
                'image' => 'products/November2016/ovLnUAgMRjB9hYGkFbmR.jpg',
                'description' => 'Keep your LEGO Springfielders satisfied by fulfilling all their shopping needs with The Simpsons LEGO Kwik-E-Mart. Springfield’s beloved convenience store features a removable roof and comes with Chief Wiggum and his cruiser.',
                'body' => '<p><img src="/storage/products/November2016/7S4U5aihxAtcQltTjmso.jpg" alt="" width="640" height="533" /></p>
<p><img src="/storage/products/November2016/4cOQcbdJnX85tXrA8Z7Y.jpg" alt="" width="640" height="533" /></p>',
                'price' => 199.95,
                'purchase_url' => 'https://www.amazon.com/dp/B00W677IOQ/',
                'slug' => 'the-simpsons-lego-kwik-e-mart',
                'meta_description' => 'The Simpsons LEGO Kwik-E-Mart',
                'meta_keywords' => 'The Simpsons LEGO Kwik-E-Mart',
                'active' => 1,
                'featured' => 0,
                'category_id' => 2,
                'created_at' => '2016-11-29 23:42:20',
                'updated_at' => '2016-11-29 23:42:20',
                'related' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'Tiny Playable Arcade Machines',
                'seo_title' => 'Tiny Playable Arcade Machines',
                'image' => 'products/November2016/ChfaKNM09Mz5XFLirlY0.jpg',
                'description' => 'Experience the fun of arcade gaming wherever you go by bringing along one of these tiny playable arcade machines. Built with an Arduino platform, each arcade has an OLED screen, analog joystick, and loads games off a microSD.',
                'body' => '<p><img src="/storage/products/November2016/XuZKOlnWazByyQRCQiEB.gif" alt="" width="100%" height="auto" /></p>',
                'price' => 75.0,
                'purchase_url' => 'https://www.kickstarter.com/projects/kenburns/tiny-arcade-a-retro-tiny-playable-game-cabinet/description',
                'slug' => 'tiny-playable-arcade-machines',
                'meta_description' => 'Tiny Playable Arcade Machines',
                'meta_keywords' => 'Tiny Playable Arcade Machines',
                'active' => 1,
                'featured' => 0,
                'category_id' => 2,
                'created_at' => '2016-11-29 23:45:07',
                'updated_at' => '2016-11-29 23:45:07',
                'related' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'Burrito Pencil Pouch',
                'seo_title' => 'Burrito Pencil Pouch',
                'image' => 'products/December2016/z72QKvcukd7sY87vQOhY.jpg',
                'description' => 'Keep your daily essentials organized by storing them inside this burrito pencil pouch. It sports a tasty looking tortilla exterior and features a functional wrap design that prevents anything from falling out.',
                'body' => '<p><img src="/storage/products/December2016/fjiS0HjxCzaN0vg6jKeR.jpg" alt="" width="100%" height="auto" /></p>',
                'price' => 12.99,
                'purchase_url' => 'https://www.amazon.com/dp/B00WG0JZOE/',
                'slug' => 'burrito-pencil-pouch',
                'meta_description' => 'Burrito Pencil Pouch',
                'meta_keywords' => 'Burrito Pencil Pouch',
                'active' => 1,
                'featured' => 0,
                'category_id' => 10,
                'created_at' => '2016-12-06 18:16:52',
                'updated_at' => '2017-07-09 17:44:52',
                'related' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'Bathtub Ball Track Set',
                'seo_title' => 'Bathtub Ball Track Set',
                'image' => 'products/December2016/xtFS1bjKySEaaTC2Z3KB.jpg',
                'description' => 'Make bath-time fun for your little ones using this bathtub ball track set. The set includes 3 tracks, a ladle, a ball, and a paddle wheel that you can easily stick onto your tile walls to create a fun maze for your little tadpole to play with.',
                'body' => '<p><img src="/storage/products/December2016/Ayk1TDGoCIB6KmzSdEQo.jpg" alt="" width="100%" height="auto" /></p>',
                'price' => 19.99,
                'purchase_url' => 'https://www.amazon.com/dp/B00BF3IO22/',
                'slug' => 'bathtub-ball-track-set',
                'meta_description' => 'Bathtub Ball Track Set',
                'meta_keywords' => 'Bathtub Ball Track Set',
                'active' => 1,
                'featured' => 0,
                'category_id' => 10,
                'created_at' => '2016-12-06 18:34:56',
                'updated_at' => '2017-07-09 17:44:53',
                'related' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'Q-Tip Crossbow',
                'seo_title' => 'Q-Tip Crossbow',
                'image' => 'products/December2016/geid8m2NMmkFvZ9tb8p9.jpg',
                'description' => 'Kick your cubicle warfare up a notch by turning your toiletries into weapons using this Q-tip crossbow. It’s compact enough to fit in your hand and comes with 25 cotton swabs you can shoot up to 20 feet in distance.',
                'body' => '',
                'price' => 9.99,
                'purchase_url' => 'http://www.thinkgeek.com/product/jklt/',
                'slug' => 'q-tip-crossbow',
                'meta_description' => 'Q-Tip Crossbow',
                'meta_keywords' => 'Q-Tip Crossbow',
                'active' => 1,
                'featured' => 0,
                'category_id' => 10,
                'created_at' => '2016-12-06 18:36:45',
                'updated_at' => '2017-01-02 04:31:18',
                'related' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'Pac-Man Suit',
                'seo_title' => 'Pac-Man Suit',
                'image' => 'products/January2017/bg6lFEXc1B90vz1pYUW5.jpg',
                'description' => 'Make the girls go waka-waka over your impeccable fashion taste by dressing up in this stunning Pac-Man suit. Every square inch of this suit comes with vintage Pac-Man graphics, featuring all the characters form the original game.',
                'body' => '<p><img src="/storage/products/January2017/bdbCEfy6mEk86XliFjtj.jpg" alt="" width="640" height="533" /></p>',
                'price' => 110.0,
                'purchase_url' => 'https://www.amazon.com/dp/B01DCWQUQU/',
                'slug' => 'pac-man-suit',
                'meta_description' => 'Make the girls go waka-waka over your impeccable fashion taste by dressing up in this stunning Pac-Man suit. Every square inch of this suit comes with vintage Pac-Man graphics, featuring all the characters form the original game.',
                'meta_keywords' => 'pac-man suit, geeky suit',
                'active' => 1,
                'featured' => 0,
                'category_id' => NULL,
                'created_at' => '2017-01-01 04:59:00',
                'updated_at' => '2017-12-07 01:53:45',
                'related' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'Knight Helmet Hat',
                'seo_title' => 'Knight Helmet Hat',
                'image' => 'products/January2017/4HbUoVlQjlbQr0jkNYXo.jpg',
                'description' => 'Look down right chivalrous while staying warm with this crocheted knight helmet hat. With its thick padded armor and functional moving visor, the knight helmet hat is sure to land you a damsel or two.',
                'body' => '<p><img src="/storage/products/January2017/D9pH9y2cEvlMOsyLrFqx.jpg" alt="" width="640" height="350" /></p>',
                'price' => 19.99,
                'purchase_url' => 'https://www.amazon.com/dp/B00CPJD9PC/',
                'slug' => 'knight-helmet-hat',
                'meta_description' => 'Look down right chivalrous while staying warm with this crocheted knight helmet hat. With its thick padded armor and functional moving visor, the knight helmet hat is sure to land you a damsel or two.',
                'meta_keywords' => 'knight hat helmet, knight helmet, crocheted knight helmet hat, crocheted hat',
                'active' => 1,
                'featured' => 0,
                'category_id' => NULL,
                'created_at' => '2016-12-03 16:58:00',
                'updated_at' => '2017-07-09 17:44:54',
                'related' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'Sock Sandals',
                'seo_title' => 'Sock Sandals',
                'image' => 'products/January2017/r3f2kRkCWnt0H22mppiA.jpg',
                'description' => 'Protect your virginity while you keeping your feet warm and cozy using these sock sandals. Made from premium cotton, these machine washable socks come with a sexy brown leather sandal design and a non-slip sole.',
                'body' => '',
                'price' => 9.98,
                'purchase_url' => 'https://www.amazon.com/dp/B00A785NOS/',
                'slug' => 'sock-sandals',
                'meta_description' => 'Protect your virginity while you keeping your feet warm and cozy using these sock sandals. Made from premium cotton, these machine washable socks come with a sexy brown leather sandal design and a non-slip sole.',
                'meta_keywords' => 'Sock Sandals',
                'active' => 1,
                'featured' => 0,
                'category_id' => NULL,
                'created_at' => '2016-12-13 15:00:00',
                'updated_at' => '2017-01-03 20:15:36',
                'related' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'Nintendo Bed Set',
                'seo_title' => 'Nintendo Bed Set',
                'image' => 'products/January2017/zuAAMZvTW9dqruf1gVKU.jpg',
                'description' => 'Geek up your room with this awesome retro NES Bed set. Take your dreams back to a time when 8-bit was all you needed. Set is complete with pillow cases and comforter blanket.',
                'body' => '<p><img src="/storage/products/January2017/B21KnlhvYWSvDAXH1ljF.jpg" alt="" width="640" height="406" /></p>',
                'price' => 0.0,
                'purchase_url' => 'http://www.instructables.com/id/NES-Bedding-set/',
                'slug' => 'nintendo-bed-set',
                'meta_description' => 'Geek up your room with this awesome retro NES Bed set. Take your dreams back to a time when 8-bit was all you needed. Set is complete with pillow cases and comforter blanket.',
                'meta_keywords' => 'Nintendo Bed Set, Nintendo Bed',
                'active' => 1,
                'featured' => 1,
                'category_id' => NULL,
                'created_at' => '2016-10-29 20:00:00',
                'updated_at' => '2017-02-07 12:52:56',
                'related' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'title' => 'Portable Super Nintendo Player',
                'seo_title' => 'Portable Super Nintendo Player',
                'image' => 'products/January2017/1jVlliZFiLNPgSEsFBHt.jpg',
                'description' => 'The Supaboy is a handheld Super Nintendo device. You can simply plug in an SNES game into the console and begin playing some of your old favorites. There are also 2 ports for external Super Nintendo Controllers.',
                'body' => '<p><img src="/storage/products/January2017/2WTxRX9dX3HeXQzQsCjH.jpg" alt="" width="640" height="533" /></p>
<p><img src="/storage/products/January2017/GvlORwk12HIbT5aJSoRJ.jpg" alt="" width="640" height="533" /></p>
<p><img src="/storage/products/January2017/zZotSukj4ip6EFjTPPbL.jpg" alt="" width="640" height="534" /></p>',
                'price' => 99.95,
                'purchase_url' => 'https://www.amazon.com/dp/B005GSRPG8/',
                'slug' => 'portable-super-nintendo-player',
                'meta_description' => 'The Supaboy is a handheld Super Nintendo device. You can simply plug in an SNES game into the console and begin playing some of your old favorites. There are also 2 ports for external Super Nintendo Controllers.',
                'meta_keywords' => 'Portable Super Nintendo, Super Nintendo, Nintendo',
                'active' => 1,
                'featured' => 0,
                'category_id' => NULL,
                'created_at' => '2016-12-29 20:11:00',
                'updated_at' => '2017-01-03 20:16:02',
                'related' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'title' => 'NES Lunchbox',
                'seo_title' => 'NES Lunchbox',
                'image' => 'products/January2017/R46ogTwpJa1rnQgRvhU6.jpg',
                'description' => 'Keep your lunch in this awesome retro Nintendo Lunchbox. This lunchbox comes with a solid nintendo case and a leather handle. Be the talk of the lunch room with this class NES lunchbox.',
                'body' => '<p><img src="/storage/products/January2017/LfNQLJ09doEEHIJx30jk.jpg" alt="" width="640" height="427" /></p>',
                'price' => 89.99,
                'purchase_url' => 'https://www.etsy.com/listing/72598274/nintendo-entertainment-system-lunch-box',
                'slug' => 'nes-lunchbox',
                'meta_description' => 'Keep your lunch in this awesome retro Nintendo Lunchbox. This lunchbox comes with a solid nintendo case and a leather handle. Be the talk of the lunch room with this class NES lunchbox.',
                'meta_keywords' => 'NES Lunchbox, Nintendo Lunchbox',
                'active' => 1,
                'featured' => 0,
                'category_id' => NULL,
                'created_at' => '2016-11-16 20:15:00',
                'updated_at' => '2017-01-03 20:15:24',
                'related' => NULL,
            ),
        ));
        
        
    }
}